name: ambient_gradient_border
description: A Flutter widget that displays a container with an animated ambient gradient glow effect around its border.
version: 0.1.0
homepage: https://github.com/psguny/ambient_gradient_border
repository: https://github.com/psguny/ambient_gradient_border
issue_tracker: https://github.com/psguny/ambient_gradient_border/issues

environment:
  sdk: '>=3.0.0 <4.0.0' # 사용하는 Dart/Flutter 버전에 맞게 조절
  flutter: ">=1.17.0" # Flutter 버전 요구사항 명시

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # 코드 스타일 검사 (권장)

# flutter 섹션은 라이브러리 자체에는 필요하지 않지만,
# 나중에 example 앱을 만들 때 필요할 수 있습니다.
# flutter:
#   uses-material-design: true

# The following section is specific to Flutter packages.
flutter:
  # This section is used to specify that this is a pure Dart package
  # with no native platform implementations